version: "3.8"

services:
  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack/data
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - la-huella-network

volumes:
  localstack-data:

networks:
  la-huella-network:
    driver: bridge
